<a href="https://colab.research.google.com/github/emilytsen/random_forest_iris/blob/main/random_forest_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

RANDOM FOREST


In [ ]:
# Importação das bibliotecas
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

from matplotlib import pyplot as plt
import pandas as pd
import numpy as np

In [ ]:
# Carrega o dataset iris
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [ ]:
iris


{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

## x = independentes
## y = dependente

In [ ]:
#divide os dados em conjunto de treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3) #70% train e 30% teste

In [ ]:
#criar um modelo de regressão logistica
model = RandomForestClassifier(n_estimators=50, min_samples_leaf=3, max_features=2, oob_score=True)

#n_estimators=50 => número de árvores

#trina o modelo
model.fit(X_train, y_train)

RandomForestClassifier(max_features=2, min_samples_leaf=3, n_estimators=50,
                       oob_score=True)

In [ ]:
# Faz previsões no conjunto de teste
y_pred = model.predict(X_test)

# Calcula a acurácia do modelo
acuracy = accuracy_score(y_test, y_pred)
print("Acurácia:", acuracy)


Acurácia: 0.9111111111111111


In [ ]:
#Média do resultados dos treinamentos das árvores
print(model.oob_score_)

0.9619047619047619


In [ ]:
#matriz de decisáo de cada árvore
print(model.oob_decision_function_)

[[0.046875   0.9375     0.015625  ]
 [0.1005291  0.8994709  0.        ]
 [0.025      0.77113095 0.20386905]
 [1.         0.         0.        ]
 [0.         0.15       0.85      ]
 [0.         0.95428571 0.04571429]
 [1.         0.         0.        ]
 [0.         1.         0.        ]
 [1.         0.         0.        ]
 [0.0787037  0.9212963  0.        ]
 [0.         0.07060185 0.92939815]
 [1.         0.         0.        ]
 [0.         0.         1.        ]
 [0.98863636 0.01136364 0.        ]
 [1.         0.         0.        ]
 [0.         0.02083333 0.97916667]
 [0.02       0.54361905 0.43638095]
 [0.         0.01785714 0.98214286]
 [0.03519669 0.93581781 0.02898551]
 [0.         0.01960784 0.98039216]
 [1.         0.         0.        ]
 [0.         0.52040816 0.47959184]
 [0.         0.99130435 0.00869565]
 [0.         0.96805556 0.03194444]
 [1.         0.         0.        ]
 [0.70869408 0.29130592 0.        ]
 [0.         0.984      0.016     ]
 [1.         0.         0.  

In [ ]:
#grau de importancia de cada atributo
print(model.feature_importances_)

[0.13331083 0.02422864 0.42568188 0.41677865]


In [ ]:
#atributos
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [ ]:
#targuet das flores
print(iris.target_names)

['setosa' 'versicolor' 'virginica']
